services:
  mysql:
    image: mysql:8.4
    container_name: water-polo-mysql
    restart: always
    environment:
      MYSQL_DATABASE: water_polo_referee_system
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: water-polo-backend
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/water_polo_referee_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: water-polo-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mysql_data: